name: opus_flutter_macos
description: MacOS implementation of the opus_flutter plugin.
repository: https://github.com/EPNW/opus_flutter/tree/master/opus_flutter_macos
version: 3.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  opus_flutter_platform_interface: ^3.0.0
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/opus_license.txt
    - assets/libopus.dylib.blob
  plugin:
    implements: opus_flutter
    platforms:
      macos:
        dartPluginClass: OpusFlutterMacOS
        pluginClass: none
